//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Team_Git_JooleMay_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductModel { get; set; }
        public string ProductType { get; set; }
        public int CategoryID { get; set; }
        public int SubCategoryID { get; set; }
        public int ManufactureID { get; set; }
        public int SeriesID { get; set; }
        public int TechnicalSpecificationID { get; set; }
        public int ProductTypeDetailsID { get; set; }
        public string ProductImgUrl { get; set; }
    
        public virtual tblManufacture tblManufacture { get; set; }
        public virtual tblProductCategory tblProductCategory { get; set; }
        public virtual tblProductSubCategory tblProductSubCategory { get; set; }
        public virtual tblProductTypeDetail tblProductTypeDetail { get; set; }
        public virtual tblSery tblSery { get; set; }
        public virtual tblTechnicalSpecification tblTechnicalSpecification { get; set; }
    }
}
