//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Team_Git_JooleMay_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProject2Product
    {
        public int ID { get; set; }
        public int ProjectID { get; set; }
        public int ProductID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int UserID { get; set; }
    }
}
