//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Team_Git_JooleMay_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductProperty
    {
        public int PropertyID { get; set; }
        public string PropertyName { get; set; }
        public Nullable<bool> IsTechSpec { get; set; }
    }
}
