//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Team_Git_JooleMay_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTechnicalSpecification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTechnicalSpecification()
        {
            this.tblProducts = new HashSet<tblProduct>();
        }
    
        public int TechnicalSpecifationID { get; set; }
        public int SubCategoryID { get; set; }
        public Nullable<decimal> AirFlow { get; set; }
        public Nullable<decimal> PowerMin { get; set; }
        public Nullable<decimal> PowerMax { get; set; }
        public Nullable<decimal> VAC_Min { get; set; }
        public Nullable<decimal> VAC_Max { get; set; }
        public Nullable<int> FanSpeedMin { get; set; }
        public Nullable<int> FanSpeedMax { get; set; }
        public Nullable<int> NumberofFanSpeed { get; set; }
        public Nullable<int> SoundAtMaxSpeed { get; set; }
        public Nullable<decimal> FanSweepDiameter { get; set; }
        public Nullable<decimal> HeightMin { get; set; }
        public Nullable<decimal> HeightMax { get; set; }
        public Nullable<decimal> Weight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduct> tblProducts { get; set; }
    }
}
