//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Team_Git_JooleMay_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTechSpecFilter
    {
        public int PropertyID { get; set; }
        public int SubCategoryID { get; set; }
        public Nullable<int> MinValue { get; set; }
        public Nullable<int> MaxValue { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
